data = [
{
	id:1,
	name: "Multi-Post Stories",
	description:"A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
	featured-img:"./pics/rec.svg",
	technologies:["CSS", "HTML", "CSS", "BootStrap", "Ruby"],
	link-live:"#",
	link-source:"#",
},
{
	id:2,
	name: "Profesional Art Printing Data",
	description:"A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
	featured-img:"./pics/rec.svg",
	technologies:["HTML", "BootStrap", "Ruby"],
	link-live:"#",
	link-source:"#",
},
{
	id:3,
	name: "Profesional Art Printing Data",
	description:"A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
	featured-img:"./pics/rec.svg",
	technologies:["HTML", "BootStrap", "Ruby"],
	link-live:"#",
	link-source:"#",
},
{
	id:4,
	name: "Profesional Art Printing Data",
	description:"A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
	featured-img:"./pics/rec.svg",
	technologies:["HTML", "BootStrap", "Ruby"],
	link-live:"#",
	link-source:"#",
},
{
	id:5,
	name: "Profesional Art Printing Data",
	description:"A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
	featured-img:"./pics/rec.svg",
	technologies:["HTML", "BootStrap", "Ruby"],
	link-live:"#",
	link-source:"#",
},
{
	id:6,
	name: "Profesional Art Printing Data",
	description:"A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
	featured-img:"./pics/rec.svg",
	technologies:["HTML", "BootStrap", "Ruby"],
	link-live:"#",
	link-source:"#",
},
{
	id:7,
	name: "Profesional Art Printing Data",
	description:"A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
	featured-img:"./pics/rec.svg",
	technologies:["HTML", "BootStrap", "Ruby"],
	link-live:"#",
	link-source:"#",
}
]